This is makeindex, version 2.15 [TeX Live 2017] (kpathsea + Thai support).
Scanning style file ./diploma-thesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file diploma-thesis.acn....done (239 entries accepted, 0 rejected).
Sorting entries.....done (1954 comparisons).
Generating output file diploma-thesis.acr....done (170 lines written, 0 warnings).
Output written in diploma-thesis.acr.
Transcript written in diploma-thesis.alg.
