FROM library/node:9.11.1

WORKDIR /usr/src/framework
COPY ./nodejs/business-context ./business-context
COPY ./nodejs/business-context-grpc ./business-context-grpc
COPY ./nodejs/business-context-xml ./business-context-xml
COPY ./proto ./proto

RUN yarn install \
    && yarn link \
    && npm run-script build \
